import { Language } from '@/types';

// Comprehensive bot response function with detailed German cuisine information
export function getBotResponse(input: string, language: Language): string {
  const inputLower = input.toLowerCase();
  
  // Common responses for English
  if (language === 'en') {
    if (inputLower.includes('hello') || inputLower.includes('hi') || inputLower.includes('hey') || inputLower.includes('greetings')) {
      return "Hello! How can I help you today?";
    } else if ((inputLower.includes('tell') && inputLower.includes('dishes')) || inputLower.includes('list dishes') || inputLower.includes('what dishes')) {
      return "Our website features the following dishes: Bavarian Pretzel, Apple Strudel, Berliner Pfannkuchen, Kartoffelpuffer, Currywurst, Kaiserschmarrn, Nuremberg Bratwurst, Bienenstich, Black Forest Cake, Bavarian Sauerkraut, Semmelknödel, Käsespätzle, Kohlroulade, Schweinshaxe, Leberkäse, Rouladen, Königsberger Klopse, Jägerschnitzel, Sauerbraten, and Wiener Schnitzel.";
    } else if (inputLower.includes('primary goal') || inputLower.includes('mission') || inputLower.includes('goal')) {
      return "Our primary goal is to promote German culinary heritage and empower food enthusiasts worldwide by providing authentic recipes, cultural context, and easy ordering options.";
    } else if ((inputLower.includes('sdg') && inputLower.includes('2')) || inputLower.includes('why sdg')) {
      return "We highlight SDG 2 (Zero Hunger) to underscore our commitment to food accessibility and sustainable practices, supporting global efforts to end hunger through cultural and culinary education.";
    } else if ((inputLower.includes('who') && inputLower.includes('made') && inputLower.includes('website')) || inputLower.includes('kabilesh')) {
      return "This website was created by Kabilesh C and Jaideep to share the rich traditions of German cuisine.";
    } else if (inputLower.includes('what is guteneats') || inputLower.includes('about guteneats') || inputLower.includes('why guteneats')) {
      return "GutenEats is a platform dedicated to authentic German cuisine, created to share the rich culinary heritage of Germany with food enthusiasts worldwide. We offer detailed information about traditional German dishes, their regional origins, cooking methods, and cultural significance. Our mission is to promote German food culture and provide an educational resource for anyone interested in exploring German gastronomy. Whether you're looking for recipes, cultural context, or just want to order authentic German food, GutenEats is your trusted companion!";
    } else if (inputLower.includes('wiener schnitzel')) {
      return "Wiener Schnitzel is an iconic Austrian-German dish consisting of a thin, breaded and pan-fried veal cutlet. The preparation involves pounding veal cutlets to about 4mm thickness, seasoning them with salt and pepper, then coating them in flour, beaten eggs, and breadcrumbs before frying in clarified butter or oil until golden brown. The perfect schnitzel should be crispy on the outside with a slight 'soufflé' effect where the coating puffs away from the meat. Traditional accompaniments include a slice of lemon, lingonberry jam, potato salad, or parsley potatoes. Cooking time is about 20-25 minutes total, including preparation. For an authentic version, use veal - though pork is commonly substituted outside Austria. Would you like our recipe or cooking tips?";
    } else if (inputLower.includes('pretzel') || inputLower.includes('brezel')) {
      return "Bavarian pretzels (Brezeln) are iconic German bakery items with a distinctive knot shape and deep brown, shiny crust. Ingredients include flour, water, yeast, salt, and food-grade lye for the traditional alkaline bath that gives pretzels their unique color and flavor. To make them, the dough is mixed, allowed to rise, shaped into the classic pretzel form, dipped in a lye solution (or baking soda alternative), sprinkled with coarse salt, and baked at high temperature (220°C/425°F) for 15-20 minutes. The result should have a crisp exterior, soft interior, and that signature chewy pretzel texture. They're traditionally served with sweet mustard, butter, or enjoyed with German beer. The entire process takes about 2-3 hours, including rising time. Pretzels have been made in Bavaria since the Middle Ages and remain a beloved snack and breakfast item throughout Germany.";
    } else if (inputLower.includes('beer') || inputLower.includes('bier')) {
      return "German beer culture is unparalleled worldwide, governed by the Reinheitsgebot (Beer Purity Law) of 1516, which originally allowed only water, barley, and hops in beer production (yeast was added later once its role was understood). Germany boasts over 1,300 breweries producing more than 7,000 different beers, each region having distinctive specialties: Bavaria is known for Helles (light lager) and Hefeweizen (wheat beer), Cologne for Kölsch (light, crisp ale), Düsseldorf for Altbier (copper-colored ale), and Berlin for Berliner Weisse (sour wheat beer). Beer is integral to German social life, with beer gardens being community gathering places. Traditional beer steins were developed with lids to protect drinks from insects during the Black Death. Germans consume about 100 liters of beer per person annually, and traditional beer accompaniments include pretzels, obatzda (cheese spread), and various wurst varieties. For the full German experience, try a beer tasting flight paired with traditional snacks!";
    } else if (inputLower.includes('sauerkraut')) {
      return "Sauerkraut is fermented cabbage and a cornerstone of German cuisine dating back centuries. To make traditional sauerkraut, you need fresh cabbage, salt (about 2-3% of the cabbage weight), and optional caraway seeds or juniper berries for flavor. The cabbage is shredded finely, mixed with salt, and pounded or pressed to extract liquid. It's then packed tightly into a fermentation container, weighted down to keep it submerged in its own juice, and left to ferment at room temperature for 2-6 weeks depending on desired sourness. The fermentation process creates beneficial probiotics while producing its characteristic tangy flavor. Sauerkraut is typically served as a side dish with pork, sausages, or as part of dishes like Choucroute garnie. It's not only delicious but also rich in vitamins C, K, and B, as well as fiber and probiotics that aid digestion. The preparation time is about 30 minutes, but patience is needed for the weeks of fermentation!";
    } else if (inputLower.includes('apple strudel') || inputLower.includes('apfelstrudel')) {
      return "Apfelstrudel (Apple Strudel) is a beloved dessert throughout Germany and Austria. This delicate pastry features a paper-thin dough wrapped around a spiced apple filling. The ingredients include flour, water, oil, and salt for the dough; and apples, sugar, cinnamon, raisins, breadcrumbs, and nuts for the filling. The special technique involves stretching the dough so thin you can read a newspaper through it! The dough is then layered with butter, topped with the apple mixture, rolled up, and baked at 190°C (375°F) for 35-40 minutes until golden brown. The total preparation time is about 2 hours, including dough resting. Traditionally served warm with a dusting of powdered sugar and vanilla sauce or vanilla ice cream. The crisp, flaky exterior gives way to tender, juicy spiced apples inside, creating a perfect balance of textures and flavors. A slice of Apfelstrudel with coffee is a classic German afternoon treat!";
    } else if (inputLower.includes('black forest cake') || inputLower.includes('schwarzwälder kirschtorte')) {
      return "Schwarzwälder Kirschtorte (Black Forest Cake) is Germany's most famous dessert worldwide. This decadent cake consists of layers of chocolate sponge soaked in Kirschwasser (cherry schnapps), filled with whipped cream and sour cherries, and covered with more whipped cream, chocolate shavings, and cherries. The ingredients include chocolate sponge cake (eggs, sugar, flour, cocoa powder), Kirschwasser, sour cherries, heavy cream, sugar, and dark chocolate for decoration. Preparation involves baking the chocolate sponges (25-30 minutes), soaking them in cherry liqueur, preparing the cherry filling, whipping the cream, and assembling the layers. The entire process takes approximately 3 hours, plus chilling time. By German law, authentic Black Forest Cake must contain Kirschwasser to bear the name. The cake originates from the Black Forest region, known for its sour cherries and cherry schnapps. The contrast between the rich chocolate, light cream, and tart cherries creates a perfectly balanced dessert that has been beloved since its creation in the 1930s.";
    } else if (inputLower.includes('currywurst')) {
      return "Currywurst is Berlin's iconic street food, created in 1949 by Herta Heuwer when she combined American ketchup with curry powder on steamed-then-fried pork sausage. The ingredients are simple: pork sausage (either with or without casing), tomato ketchup, curry powder, Worcestershire sauce, and sometimes a touch of paprika or chili powder. To prepare authentic currywurst, the sausage is first steamed, then fried until crispy on the outside (about 10 minutes total cooking time). It's then sliced and topped with the special curry-ketchup sauce and a generous sprinkle of curry powder. The dish is traditionally served with a small wooden fork on a paper plate with French fries or a bread roll. The preparation is quick - about 15-20 minutes total. This popular fast food is enjoyed by all social classes in Germany, with some 800 million servings consumed annually nationwide. In Berlin, you'll find both styles - with casing (knackwurst) or without (bratwurst) - each with dedicated fans claiming theirs is the authentic version.";
    } else if (inputLower.includes('sauerbraten')) {
      return "Sauerbraten is considered the national dish of Germany - a marinated pot roast that showcases the German talent for transforming tough cuts of meat into tender delicacies. The dish requires beef (traditionally horse meat in some regions, though beef is now standard), vinegar, wine, onions, carrots, celery, bay leaves, juniper berries, cloves, and peppercorns for the marinade. The meat marinates in this mixture for 3-7 days before being slowly braised for 2-3 hours. The remarkable finishing touch is the gravy, made from the strained marinade thickened with crushed gingersnap cookies (Lebkuchen), which adds a subtle sweetness balancing the sourness. Total preparation time is 3-7 days for marinating plus 3 hours cooking. Sauerbraten is typically served with potato dumplings (Kartoffelklöße) and red cabbage (Rotkohl), creating a harmony of flavors that represents the essence of German cuisine. Each region has its own variation - Rheinischer Sauerbraten from the Rhineland is the most famous, while versions from Frankfurt, Swabia, and Saxony all have distinct characteristics.";
    } else if (inputLower.includes('schweinshaxe') || inputLower.includes('pork knuckle')) {
      return "Schweinshaxe is a quintessential Bavarian specialty featuring a roasted pork knuckle (ham hock) with crackling-crisp skin and meltingly tender meat inside. The ingredients are simple: a raw pork knuckle (about 1.2-1.5kg), salt, pepper, caraway seeds, garlic, and sometimes dark beer for basting. Preparation involves scoring the skin in a diamond pattern to help render the fat and create the perfect crackling. The knuckle is seasoned generously, then roasted in a low oven (160°C/320°F) for about 2 hours before increasing the temperature to 220°C/430°F for the final 20-30 minutes to crisp the skin. Some recipes include a beer-based brine or involve simmering the haxe in stock before roasting. The total cooking time is approximately 2.5-3 hours. The perfect Schweinshaxe should have a crisp, golden-brown exterior that crackles when tapped, while the meat inside is juicy and falls off the bone. It's traditionally served with sauerkraut, potato dumplings, and a rich beer gravy, accompanied by a large stein of dark Bavarian beer.";
    } else if (inputLower.includes('spätzle') || inputLower.includes('spaetzle')) {
      return "Spätzle are hand-crafted egg noodles from southern Germany, particularly beloved in Swabia. These small, irregular-shaped pasta bits have a delightfully chewy texture and are made from a simple batter of flour, eggs, water, and salt - the high egg content (traditionally one egg per 100g flour) gives them their distinctive yellow color and rich taste. The preparation is unique: a wet, sticky dough is prepared and then either pushed through a special spätzle maker, coarse colander, or scraped from a wooden board directly into boiling water, where they cook for just 2-3 minutes until they float. Total preparation time is about 20-30 minutes. When served as Käsespätzle (the German answer to mac and cheese), they're layered with Emmental or Gruyère cheese and topped with caramelized onions. Spätzle accompany many classic German dishes, especially those with rich gravies. The name 'Spätzle' means 'little sparrows' in Swabian dialect, referring to their shape. A good Spätzle has a slightly firm exterior with a tender, almost dumpling-like interior that perfectly catches sauces.";
    } else if (inputLower.includes('rouladen')) {
      return "Rouladen are thin slices of beef wrapped around a filling of bacon, onions, mustard, and pickles - a perfect example of German home cooking ingenuity. The ingredients include thinly sliced beef (usually topside or silverside, about 3-4mm thick), bacon, onions, German mustard, dill pickles, salt, pepper, and beef broth. To prepare, each beef slice is spread with mustard, topped with bacon, chopped onions, and pickle spears, then rolled up and secured with toothpicks or cooking twine. The rolls are seasoned, seared on all sides (about 5 minutes), then slowly braised in beef broth with vegetables for 1.5-2 hours until fork-tender. The cooking liquid is then strained and thickened to create a rich gravy. Total preparation and cooking time is approximately 2.5 hours. Rouladen are traditionally served with potato dumplings (Knödel) or mashed potatoes, and red cabbage or Brussels sprouts. This dish is typically enjoyed for Sunday family dinners or special occasions throughout Germany, with regional variations in the filling sometimes including minced meat, different herbs, or even boiled eggs.";
    } else if (inputLower.includes('bienenstich') || inputLower.includes('bee sting cake')) {
      return "Bienenstich (Bee Sting Cake) is a traditional German dessert featuring a sweet yeast dough topped with caramelized almonds and filled with vanilla custard cream. The name supposedly comes from a legend about bakers who were attacked by bees attracted to the honey topping while making this cake. The ingredients include yeast dough (flour, yeast, milk, butter, sugar, eggs), almond topping (sliced almonds, butter, sugar, honey, cream), and vanilla custard filling (milk, egg yolks, sugar, cornstarch, vanilla). Preparation involves making and rising the yeasted dough (about 1 hour), preparing the almond topping, baking the cake (25-30 minutes at 180°C/350°F), and making the custard filling. Once cooled, the cake is sliced horizontally and filled with the custard. Total preparation time is approximately 3 hours including cooling time. The contrast between the crunchy, caramelized almond topping, the light yeast dough, and the creamy vanilla filling makes this a uniquely satisfying dessert. Bienenstich is a popular choice for afternoon coffee (Kaffee und Kuchen), an important social tradition in German culture.";
    } else if (inputLower.includes('thank') || inputLower.includes('thanks')) {
      return "You're very welcome! I'm always here to help with your German culinary questions. Feel free to ask about anything else – recipes, ingredients, cultural traditions, or placing an order. Guten Appetit!";
    } else if (inputLower.includes('recipe')) {
      return "I'd be delighted to share recipes with you! Our website has detailed recipes for classics like Sauerbraten, Spätzle, Black Forest Cake, and many more. Each recipe includes step-by-step instructions, chef's tips, and cultural background. Is there a specific German dish you'd like to learn how to make?";
    } else if (inputLower.includes('ingredients')) {
      return "German cuisine features key ingredients like quality pork and beef, potatoes, cabbage, mustard, and various herbs like caraway, juniper, and marjoram. Regional specialties might include unique local ingredients – like white asparagus (Spargel) which causes a nationwide frenzy during its short spring season! What ingredient are you curious about?";
    } else if (inputLower.includes('recommendation') || inputLower.includes('suggest') || inputLower.includes('best dish')) {
      return "For first-time explorers of German cuisine, I'd recommend starting with Schweinshaxe (crispy pork knuckle), Käsespätzle (cheese noodles; think German mac & cheese!), or a classic Bratwurst with mustard. For dessert, nothing beats Black Forest Cake or Apfelstrudel. Would you like more details about any of these dishes?";
    } else if (inputLower.includes('hungry')) {
      return "You've come to the right place! Our most popular comfort foods include hearty Gulaschsuppe (goulash soup), Rouladen (beef rolls), or for something quicker, a Döner Kebab - which was actually perfected in Berlin and is now Germany's most popular fast food! Shall I add something to your cart?";
    } else if (inputLower.includes('german')) {
      return "German cuisine varies greatly by region! Northern Germany is known for seafood dishes like Pannfisch (pan-fried fish) and Labskaus. Central Germany features hearty meat dishes like Sauerbraten and Kassler (smoked pork chop). The south offers specialties like Spätzle, Maultaschen (similar to ravioli), and Bavarian classics like pretzels and Weisswurst. The east has unique offerings like Soljanka (spicy soup) influenced by Slavic cooking. Would you like to explore a specific regional cuisine?";
    } else if (inputLower.includes('regional') || inputLower.includes('region')) {
      return "Germany has incredibly diverse regional cuisines! Bavaria is known for meat dishes like Schweinshaxe, wheat beer, and pretzels. Swabia offers Maultaschen (German ravioli) and Spätzle. Hamburg features seafood and Labskaus (corned beef with beetroot). The Rhineland is famous for Sauerbraten and Himmel und Erde (heaven and earth - potatoes and apples). Berlin has its street food culture with Currywurst and Döner Kebab. Which region's food interests you most?";
    } else if (inputLower.includes('help')) {
      return "I'm here to assist with all things German cuisine! You can ask me about specific dishes, ingredients, cooking techniques, cultural food traditions, or help with navigating our menu and placing orders. What would you like to know?";
    } else if (inputLower.includes('order') || inputLower.includes('delivery')) {
      return "Our ordering process is simple! Just add your favorite dishes to the cart, proceed to checkout, fill in your delivery details, and confirm your order. We deliver throughout the city with a standard delivery time of 30-45 minutes, and you'll receive live updates via email. For orders over €30, delivery is free! Can I help you place an order?";
    } else if (inputLower.includes('vegetarian') || inputLower.includes('vegan')) {
      return "German cuisine offers wonderful vegetarian options! Käsespätzle (egg noodles with melted cheese and crispy onions), Kartoffelpuffer (potato pancakes) with apple sauce, and Semmelknödel (bread dumplings) with mushroom sauce are classics. For vegans, we offer modern takes on traditional dishes, like mushroom-based Schnitzel and plant-based Currywurst. Our menu clearly marks all vegetarian and vegan options. Would you like me to point out some specific dishes?";
    } else if (inputLower.includes('payment') || inputLower.includes('pay')) {
      return "We accept all major credit cards, PayPal, Apple Pay, Google Pay, and cash on delivery. Our payment processing is secure and compliant with the latest standards. For regular customers, we also offer a convenient monthly billing option. All payments are processed at checkout, and you'll receive an immediate confirmation via email. Is there a specific payment method you'd like to use?";
    } else if (inputLower.includes('open') || inputLower.includes('hours') || inputLower.includes('time')) {
      return "Our restaurant is open Monday through Thursday from 11:00 AM to 10:00 PM, and Friday through Sunday from 11:00 AM to 11:00 PM. Our kitchen stops taking orders 30 minutes before closing. For holidays, we often have special hours, which are announced on our homepage. Our online ordering system accepts orders 24/7 for advance bookings. Can I help you plan your visit?";
    } else if (inputLower.includes('spicy')) {
      return "Traditional German cuisine tends to be flavorful but mild on the spice scale. However, dishes like Currywurst incorporate a nice warmth through curry powder and paprika. Our menu allows customization of spice levels for many dishes. If you enjoy spicier food, I recommend trying our \"Feurige Bratwurst\" (fiery sausage) or our chef's special Scharfes Gulasch (spicy goulash). How spicy do you prefer your food?";
    } else if (inputLower.includes('allergen') || inputLower.includes('allergy')) {
      return "Food safety is our priority! Our menu clearly labels all common allergens, and our kitchen staff receives special training for allergy concerns. For severe allergies, we have dedicated preparation areas to prevent cross-contamination. Please note any allergies in your order notes, and our chef will personally ensure your meal is safely prepared. For detailed allergen information on specific dishes, I'm happy to provide it. What allergies should we be aware of?";
    } else if (inputLower.includes('dessert') || inputLower.includes('sweet')) {
      return "German desserts are a delightful finale to any meal! Black Forest Cake (Schwarzwälder Kirschtorte) with chocolate, cherries, and whipped cream is our most famous. Apfelstrudel is a warm apple pastry served with vanilla sauce. Don't miss Bienenstich (Bee Sting Cake) with honey-almond topping and vanilla custard filling. For something simpler, try Dampfnudeln (sweet yeast dumplings) or German pancakes. Would you like a recommendation based on your taste preferences?";
    } else if (inputLower.includes('bread') || inputLower.includes('brot')) {
      return "German bread culture is so significant that it's been recognized by UNESCO as cultural heritage! With over 300 varieties, German bread ranges from dense, whole-grain Vollkornbrot to crusty wheat Brötchen (rolls). Sourdough is the foundation of many traditional recipes, creating distinctive flavors and improved digestibility. Our bakery offers fresh, authentic German breads daily, baked using traditional methods. Would you like to know about specific varieties or how to best enjoy them?";
    } else if (inputLower.includes('christmas') || inputLower.includes('holiday')) {
      return "German Christmas food traditions are magical! The holiday season features special treats like Lebkuchen (gingerbread), Stollen (fruit bread with marzipan), and Zimtsterne (cinnamon stars). Christmas markets serve Glühwein (mulled wine), roasted chestnuts, and hearty dishes like Bratwurst and Flammlachs (flame-grilled salmon). Christmas dinner often features goose, duck, or carp, with red cabbage and potato dumplings. Would you like our special holiday menu or recipes for traditional German Christmas treats?";
    } else if (inputLower.includes('wurst') || inputLower.includes('sausage')) {
      return "Germany boasts over 1,500 varieties of wurst (sausage), each region proudly offering their own specialties! Some essentials include Bratwurst (grilled sausage), Weisswurst (white veal sausage from Bavaria, traditionally eaten before noon), Knackwurst (garlicky and snappy), Leberwurst (liverwurst), and Blutwurst (blood sausage). Each has specific serving traditions - Weisswurst is peeled and eaten with sweet mustard, while Bratwurst is often served in a roll with mustard or curry ketchup for Currywurst. Would you like to know more about a specific type?";
    } else if (inputLower.includes('potato') || inputLower.includes('kartoffel')) {
      return "Potatoes are the cornerstone of German cuisine, introduced in the 18th century and now featured in countless beloved dishes! You'll find them as Kartoffelsalat (potato salad, served warm in southern Germany and cold in the north), Bratkartoffeln (fried potatoes with bacon and onions), Kartoffelpuffer (potato pancakes), Kartoffelklöße (potato dumplings), and Kartoffelgratin (potato gratin). Germans consume an average of 57kg of potatoes per person annually! Would you like to know more about how we prepare them in our dishes?";
    } else if (inputLower.includes('kartoffelpuffer')) {
      return "Kartoffelpuffer (potato pancakes) are a beloved German comfort food enjoyed throughout the country. These crispy, golden pancakes are made from grated raw potatoes, onions, eggs, flour, and seasonings. The potatoes are shredded finely, then excess moisture is squeezed out (this is crucial for crispness!). The mixture is formed into palm-sized flat cakes and shallow-fried in oil for 3-4 minutes per side until golden brown and crispy on the outside while remaining tender inside. Total preparation and cooking time is about 30 minutes. Traditionally served hot with apple sauce, sour cream, or herbed quark for sweet or savory options. During Christmas markets, they're a popular street food. Regional variations include Reibekuchen in the Rhineland and Reiberdatschi in Bavaria. They're perfect as a side dish, light meal, or snack - crispy on the outside with a soft interior and that unmistakable potato comfort!";
    } else if (inputLower.includes('maultaschen')) {
      return "Maultaschen are the German answer to ravioli - large, square pasta pockets filled with a savory mixture of ground meat, spinach, bread crumbs, and herbs! This Swabian specialty has a fascinating origin story - supposedly, monks created them during Lent to 'hide' meat from God inside the pasta (earning them the nickname 'Herrgottsbescheißerle' or 'little God-cheaters'). To make them, prepare a simple egg pasta dough (flour, eggs, water, salt) and a filling of ground meat (usually pork and beef), spinach, soaked bread, onions, and herbs. The dough is rolled thin, filled, sealed, and either simmered in broth for 10-15 minutes or pan-fried until golden. Total preparation time is about 1.5-2 hours. They're typically served either in a clear broth (in der Brühe) or sliced and fried with eggs and onions (geschmälzt). UNESCO has recognized Maultaschen as a cultural heritage food. Each household in Swabia has their own special recipe, often passed down through generations.";
    } else if (inputLower.includes('berliner') || inputLower.includes('pfannkuchen') || inputLower.includes('donut')) {
      return "Berliner Pfannkuchen (often simply called 'Berliner') are traditional German donuts without a hole! These fluffy yeast pastries feature a sweet dough (flour, eggs, butter, sugar, yeast) that's formed into balls, proved until doubled in size, deep-fried at 175°C/350°F until golden (about 3 minutes per side), and then filled with jam (traditionally raspberry) using a piping bag. They're finished with a dusting of powdered sugar or a simple glaze. Total preparation time is about 2.5 hours including proving time. During carnival season (especially on New Year's Eve and Rose Monday), a fun tradition is to secretly fill one Berliner with mustard among a batch of jam-filled ones! In Berlin, they're actually called Pfannkuchen, while in other parts of Germany they're known as Berliner or Krapfen. Modern variations include fillings like chocolate, custard, advocaat (egg liqueur), or plum butter. The perfect Berliner has a light, airy interior, a slightly crisp exterior, and generous filling in the center.";
    } else if (inputLower.includes('nuremberg') || inputLower.includes('bratwurst')) {
      return "Nuremberg Bratwurst (Nürnberger Rostbratwurst) is a protected geographical indication (PGI) specialty that must be produced within the city limits of Nuremberg to bear the name. These small, finger-sized sausages (7-9cm long, weighing about 25g each) are made from coarsely ground pork flavored with distinctive marjoram, salt, pepper, ginger, cardamom, and sometimes lemon peel. Unlike other German sausages, they contain no preservatives. They're traditionally grilled over beechwood fire, giving them their characteristic smoky flavor, and cooked for about 5-8 minutes until browned and juicy. Typically served in sets of 6, 8, 10 or 12 ('Sechs auf Kraut', 'Acht auf Kraut', etc.) on a pewter plate with sauerkraut or potato salad, and accompanied by horseradish or mustard. You can also enjoy them as 'Drei im Weckla' - three sausages in a small roll. The recipe dates back to the 14th century, and about 3 million are produced daily! Their small size allegedly originated because innkeepers could sell them through keyholes after curfew during medieval times.";
    } else if (inputLower.includes('kaiserschmarrn')) {
      return "Kaiserschmarrn is a fluffy, shredded pancake dish that was reportedly a favorite of Austrian Emperor Franz Joseph I (hence the name 'Emperor's Mess'). This comfort food has become a beloved dessert throughout Germany as well. The ingredients include eggs (separated and whites beaten to stiff peaks), flour, milk, sugar, vanilla, a pinch of salt, butter for cooking, and raisins (traditionally soaked in rum). The batter is poured into a hot buttered pan and cooked until golden on the bottom. Then comes the signature technique: the partially cooked pancake is torn into pieces with two forks, flipped in sections, and finished until caramelized and fluffy. Preparation time is about 20-25 minutes. Kaiserschmarrn is traditionally served dusted with powdered sugar and accompanied by fruit compotes - apple sauce, plum compote (Zwetschgenröster), or lingonberry preserves are classic choices. In mountain regions, it's often enjoyed as a hearty main dish after hiking. The dish achieves a perfect texture contrast between the caramelized exterior and cloud-like interior.";
    } else if (inputLower.includes('kohlroulade') || inputLower.includes('cabbage roll')) {
      return "Kohlrouladen (cabbage rolls) are a perfect example of Germany's hearty, comforting home cooking. To prepare them, you need cabbage leaves (savoy or white cabbage), ground meat (usually a mixture of beef and pork), onions, breadcrumbs or soaked rolls, eggs, herbs (marjoram, parsley), spices, and beef or vegetable broth. Large cabbage leaves are blanched until pliable (about 2-3 minutes), then filled with the meat mixture, rolled into neat packages, and secured with toothpicks or kitchen twine. They're then slowly braised in seasoned broth for about 45-60 minutes until the cabbage is tender and the filling is cooked through. Total preparation time is approximately 1.5 hours. The cooking liquid is often thickened to create a sauce. Kohlrouladen are typically served with boiled potatoes or mashed potatoes and the sauce from cooking. This economical yet delicious dish has variations throughout Eastern and Central Europe and represents the resourceful nature of traditional German cooking, transforming simple ingredients into satisfying meals. Some regional versions include bacon, sauerkraut, or rice in the filling.";
    } else if (inputLower.includes('leberkäse')) {
      return "Leberkäse (literally 'liver cheese') typically contains neither liver nor cheese! This Bavarian specialty is a finely ground meat loaf made from very finely minced pork, beef, bacon, and onions, seasoned with marjoram, salt, pepper, and sometimes garlic. The ingredients are processed into an extremely fine paste, packed into a rectangular bread pan, and baked at a high temperature (180°C/350°F) for about 1-1.5 hours until it develops a crispy brown crust while remaining moist inside. Preparation time, including baking, is approximately 2 hours. The texture is similar to a very fine bologna or smooth pâté. Leberkäse is commonly served warm in thick slices on a Semmel (roll) with sweet mustard, or cold as part of a traditional Bavarian breakfast. In Munich's beer gardens, Leberkäse Semmel is a popular quick meal. Regional variations include Pferdeleberkäse (made with horse meat), Käseleberkäse (with cheese chunks), and Pikanter Leberkäse (with pickles and paprika). The dish dates back to the early 19th century and remains a beloved Bavarian classic.";
    } else if (inputLower.includes('königsberger klopse')) {
      return "Königsberger Klopse are German meatballs named after the former East Prussian capital Königsberg (now Kaliningrad, Russia). This dish features tender meatballs made from finely ground veal (traditionally) or a mixture of ground beef and pork, soaked rolls, onions, eggs, anchovy or herring (for umami), and herbs. The meatballs are gently simmered in salt water or broth with peppercorns, bay leaves, and onions for about 15-20 minutes. What makes this dish distinctive is its creamy white sauce, made by creating a roux, adding the cooking liquid, and finishing with capers, lemon juice, and a liaison of egg yolks and cream. The total preparation time is approximately 45 minutes. Traditionally served with boiled potatoes and sliced beets or pickled red cabbage. Despite its East Prussian origins, this dish became popular throughout Germany after WWII when refugees brought their regional recipes westward. It's considered a classic of German cuisine and is often featured on restaurant menus as a lunchtime special. The combination of tangy capers, bright lemon, and rich, creamy sauce makes this comfort food truly special.";
    } else if (inputLower.includes('jägerschnitzel')) {
      return "Jägerschnitzel (Hunter's Schnitzel) is a popular German dish featuring a pan-fried pork cutlet topped with a rich mushroom sauce. Unlike Wiener Schnitzel, Jägerschnitzel is typically not breaded (though some regional versions are). The dish starts with pork loin cutlets (150-180g each) pounded thin, seasoned with salt and pepper, and quickly pan-fried in butter until golden and just cooked through (about 2-3 minutes per side). The distinctive sauce features sautéed onions, mixed mushrooms (traditionally wild mushrooms, hence the 'hunter' name), bacon, white wine, cream, and fresh herbs like parsley and thyme. The sauce is simmered for about 10-15 minutes until rich and flavorful. Total preparation time is approximately 30 minutes. Jägerschnitzel is traditionally served with Spätzle, potato pancakes, or fried potatoes, and often accompanied by a small salad or lingonberry preserves. In the former East Germany, a different dish called Jägerschnitzel consisted of a breaded and fried slice of Jagdwurst (a type of sausage) topped with tomato sauce - this version is still popular in eastern regions of Germany today.";
    } else if (inputLower.includes('semmelknödel')) {
      return "Semmelknödel (bread dumplings) are a classic Bavarian and Austrian side dish that wonderfully showcases German resourcefulness in using leftover bread. To make them, you need stale bread rolls (Semmeln), milk, eggs, onions, parsley, butter, nutmeg, salt, and pepper. The stale rolls are cut into small cubes, soaked in warm milk, and mixed with sautéed onions, beaten eggs, chopped parsley, and seasonings. After resting for about 30 minutes, the mixture is formed into tennis ball-sized dumplings (wet hands help prevent sticking) and gently simmered in lightly salted water for 15-20 minutes. Total preparation time is about 1 hour. The perfect Semmelknödel should be light and fluffy, not dense or soggy. They're traditionally served with roast meats and gravy, goulash, mushroom sauce, or in a vegetarian context with creamed spinach or a simple butter and herb topping. In Bavarian cuisine, leftover dumplings are often sliced and pan-fried with eggs the next day (Semmelknödel mit Ei). Regional variations include adding bacon, cheese, or spinach to the basic dough. These dumplings are an essential component of Sunday family meals throughout southern Germany.";
    } else if (inputLower.includes('käsespätzle')) {
      return "Käsespätzle is the German answer to mac and cheese - but with a distinctive twist! This hearty comfort food from Swabia and Allgäu combines freshly made Spätzle (egg noodles) with layers of melted cheese and caramelized onions. To make it, prepare a Spätzle batter with flour, eggs (traditionally one egg per 100g flour), water, salt, and sometimes a hint of nutmeg. The batter is pushed through a Spätzle maker, coarse grater, or colander directly into boiling water, where they cook in 2-3 minutes until they float. Meanwhile, thinly sliced onions are slowly caramelized in butter until golden brown (about 15-20 minutes). The cooked Spätzle are layered in a baking dish with grated cheese (traditionally Emmentaler or mountain cheese like Bergkäse, but Gruyère works well too) and briefly baked until the cheese melts and forms strings when pulled. Total preparation time is about 45 minutes. The dish is topped with the caramelized onions and chopped chives, and traditionally served in the communal baking dish. The ideal Käsespätzle has a perfect balance of tender noodles, gooey, stretchy cheese, and sweet onions. It's typically enjoyed with a simple green salad to cut the richness.";
    } else if (inputLower.includes('bavarian sauerkraut')) {
      return "Bavarian Sauerkraut (Bayerisches Sauerkraut) is milder and sweeter than standard sauerkraut, featuring a distinctive flavor profile created by the addition of apples, onions, and traditional Bavarian spices. To prepare it, you need fermented sauerkraut (ideally drained and rinsed slightly to reduce sourness), onions, apples, bacon or goose fat, caraway seeds, juniper berries, bay leaves, cloves, sugar, and sometimes a splash of white wine or beer. Everything is slowly simmered together for about 45-60 minutes, allowing the flavors to meld while the sauerkraut softens and takes on a golden hue from the rendered fat. Total preparation time is approximately 1 hour. The result is less acidic than regular sauerkraut, with a balanced sweet-sour profile and aromatic depth from the spices. Bavarian sauerkraut is the traditional accompaniment to Schweinshaxe (pork knuckle), Weisswurst (white sausage), and other Bavarian meat dishes. It's also essential for Choucroute garnie, a dish adopted from neighboring Alsace. The beauty of this dish lies in its transformation of simple fermented cabbage into a complex, nuanced side dish that complements the rich flavors of Bavarian cuisine.";
    } else {
      return "Thank you for your interest in German cuisine! I'd be happy to tell you more about specific dishes, ingredients, regional specialties, or cooking methods. You can also ask about our menu, ordering process, or cultural food traditions. Is there something specific about German food culture you'd like to explore?";
    }
  }
  // German responses
  else if (language === 'de') {
    if (inputLower.includes('hallo') || inputLower.includes('guten tag')) {
      return "Hallo! Wie kann ich Ihnen heute helfen?";
    } else if (inputLower.includes('was ist guteneats') || inputLower.includes('über guteneats') || inputLower.includes('warum guteneats')) {
      return "GutenEats ist eine Plattform, die sich der authentischen deutschen Küche widmet und geschaffen wurde, um das reiche kulinarische Erbe Deutschlands mit Feinschmeckern weltweit zu teilen. Wir bieten detaillierte Informationen über traditionelle deutsche Gerichte, ihre regionalen Ursprünge, Zubereitungsmethoden und kulturelle Bedeutung. Unsere Mission ist es, die deutsche Esskultur zu fördern und eine Bildungsressource für jeden zu bieten, der sich für die deutsche Gastronomie interessiert. Ob Sie nach Rezepten, kulturellem Kontext suchen oder einfach authentisches deutsches Essen bestellen möchten, GutenEats ist Ihr vertrauenswürdiger Begleiter!";
    } else if (inputLower.includes('schnitzel')) {
      return "Ah, Wiener Schnitzel! Ein Meisterwerk der österreichisch-deutschen Küche. Es handelt sich um ein dünnes, paniertes und gebratenes Kalbsschnitzel, das traditionell mit einer Scheibe Zitrone und Kartoffelsalat serviert wird. Das Geheimnis liegt darin, das Fleisch sehr dünn zu klopfen und schnell bei hoher Hitze zu braten. Die Panade sollte sich leicht vom Fleisch abheben – wir nennen das \"Soufflieren\". Möchten Sie wissen, wie Sie es zu Hause zubereiten können, oder mehr über die spezielle Version unseres Restaurants erfahren?";
    } else if (inputLower.includes('sauerbraten')) {
      return "Sauerbraten ist das Kronjuwel der deutschen Schmorbraten! Dieser 'saure Braten' besteht aus Rindfleisch, das 2-5 Tage in einer Mischung aus Essig, Wein, Kräutern und Gewürzen mariniert wird. Die lange Marinierung macht das Fleisch zart und entwickelt seine komplexen Aromen. Nach dem langsamen Garen wird die Marinade zu einer reichhaltigen Soße verarbeitet, die traditionell mit zerkleinerten Lebkuchen angedickt wird, was eine subtile Süße verleiht, die die Säure ausgleicht. Dieses Gericht stammt aus dem Rheinland und wird typischerweise mit Rotkohl und Kartoffelklößen serviert. Möchten Sie unser authentisches Rezept?";
    } else if (inputLower.includes('schweinshaxe')) {
      return "Schweinshaxe ist eine typisch bayerische Spezialität - ein gebratener Schweinshachsen mit knuspriger Kruste und zartem, saftigem Fleisch im Inneren! Die Zubereitung umfasst das Einschneiden der Haut in einem Rautenmuster, das Würzen mit Salz, Pfeffer, Kümmel und Knoblauch und dann das langsame Braten für etwa 2-3 Stunden. Der abschließende Temperaturschub sorgt für die perfekte Kruste. Sie wird traditionell mit Kartoffelknödeln und Sauerkraut sowie einer dunklen Biersoße serviert. Dieses herzhafte Gericht ist ein Klassiker bei Oktoberfestfeiern und in bayerischen Bierhallen. Möchten Sie die besondere Technik unseres Küchenchefs für die perfekte Kruste kennenlernen?";
    } else if (inputLower.includes('danke')) {
      return "Sehr gerne! Ich stehe Ihnen jederzeit für Fragen zur deutschen Küche zur Verfügung. Zögern Sie nicht, nach Rezepten, Zutaten, kulturellen Traditionen oder einer Bestellung zu fragen. Guten Appetit!";
    } else if (inputLower.includes('rezept')) {
      return "Ich teile gerne Rezepte mit Ihnen! Unsere Website bietet detaillierte Rezepte für Klassiker wie Sauerbraten, Spätzle, Schwarzwälder Kirschtorte und viele mehr. Jedes Rezept enthält Schritt-für-Schritt-Anleitungen, Tipps vom Küchenchef und kulturellen Hintergrund. Gibt es ein bestimmtes deutsches Gericht, das Sie gerne zubereiten möchten?";
    } else if (inputLower.includes('hilfe')) {
      return "Ich bin hier, um Ihnen bei allem rund um die deutsche Küche zu helfen! Sie können mich nach bestimmten Gerichten, Zutaten, Kochtechniken, kulturellen Essenstraditionen fragen oder Hilfe beim Navigieren durch unser Menü und bei der Bestellung erhalten. Was möchten Sie wissen?";
    } else {
      return "Vielen Dank für Ihr Interesse an der deutschen Küche! Ich gebe Ihnen gerne weitere Informationen zu bestimmten Gerichten, Zutaten, regionalen Spezialitäten oder Kochtechniken. Sie können auch Fragen zu unserem Menü, dem Bestellvorgang oder kulturellen Essenstraditionen stellen. Gibt es etwas Bestimmtes über die deutsche Esskultur, das Sie erkunden möchten?";
    }
  }
  // Spanish responses
  else if (language === 'es') {
    if (inputLower.includes('hola')) {
      return "¡Hola! ¿Cómo puedo ayudarte hoy?";
    } else if (inputLower.includes('qué es guteneats') || inputLower.includes('sobre guteneats') || inputLower.includes('por qué guteneats')) {
      return "GutenEats es una plataforma dedicada a la auténtica cocina alemana, creada para compartir el rico patrimonio culinario de Alemania con entusiastas de la comida en todo el mundo. Ofrecemos información detallada sobre platos tradicionales alemanes, sus orígenes regionales, métodos de cocción y significado cultural. Nuestra misión es promover la cultura alimentaria alemana y proporcionar un recurso educativo para cualquier persona interesada en explorar la gastronomía alemana. Ya sea que esté buscando recetas, contexto cultural o simplemente quiera pedir comida alemana auténtica, ¡GutenEats es su compañero de confianza!";
    } else if (inputLower.includes('gracias')) {
      return "¡De nada! Siempre estoy aquí para ayudar con sus preguntas culinarias alemanas. No dude en preguntar sobre cualquier otra cosa: recetas, ingredientes, tradiciones culturales o cómo realizar un pedido. ¡Guten Appetit!";
    } else if (inputLower.includes('receta')) {
      return "¡Me encantaría compartir recetas contigo! Nuestro sitio web tiene recetas detalladas para clásicos como Sauerbraten, Spätzle, Pastel de la Selva Negra y muchos más. Cada receta incluye instrucciones paso a paso, consejos del chef y trasfondo cultural. ¿Hay algún plato alemán específico que le gustaría aprender a preparar?";
    } else if (inputLower.includes('ayuda')) {
      return "¡Estoy aquí para ayudar con todo lo relacionado con la cocina alemana! Puede preguntarme sobre platos específicos, ingredientes, técnicas de cocina, tradiciones culturales alimentarias o ayuda para navegar por nuestro menú y realizar pedidos. ¿Qué le gustaría saber?";
    } else {
      return "¡Gracias por su interés en la cocina alemana! Me complacería contarle más sobre platos específicos, ingredientes, especialidades regionales o métodos de cocina. También puede preguntar sobre nuestro menú, proceso de pedido o tradiciones alimentarias culturales. ¿Hay algo específico sobre la cultura alimentaria alemana que le gustaría explorar?";
    }
  }
  // French responses
  else {
    if (inputLower.includes('bonjour') || inputLower.includes('salut')) {
      return "Bonjour ! Comment puis-je vous aider aujourd'hui ?";
    } else if (inputLower.includes("qu'est-ce que guteneats") || inputLower.includes('à propos de guteneats') || inputLower.includes('pourquoi guteneats')) {
      return "GutenEats est une plateforme dédiée à la cuisine allemande authentique, créée pour partager le riche patrimoine culinaire de l'Allemagne avec les amateurs de nourriture du monde entier. Nous offrons des informations détaillées sur les plats traditionnels allemands, leurs origines régionales, les méthodes de cuisson et leur importance culturelle. Notre mission est de promouvoir la culture alimentaire allemande et de fournir une ressource éducative pour toute personne intéressée à explorer la gastronomie allemande. Que vous recherchiez des recettes, du contexte culturel ou que vous souhaitiez simplement commander de la nourriture allemande authentique, GutenEats est votre compagnon de confiance !";
    } else if (inputLower.includes('merci')) {
      return "Je vous en prie ! Je suis toujours là pour vous aider avec vos questions culinaires allemandes. N'hésitez pas à me demander autre chose - recettes, ingrédients, traditions culturelles ou comment passer une commande. Guten Appetit !";
    } else if (inputLower.includes('recette')) {
      return "Je serais ravi de partager des recettes avec vous ! Notre site Web propose des recettes détaillées pour des classiques comme le Sauerbraten, le Spätzle, le gâteau de la Forêt-Noire et bien d'autres. Chaque recette comprend des instructions étape par étape, des conseils de chef et un contexte culturel. Y a-t-il un plat allemand spécifique que vous aimeriez apprendre à préparer ?";
    } else if (inputLower.includes('aide')) {
      return "Je suis là pour vous aider avec tout ce qui concerne la cuisine allemande ! Vous pouvez me poser des questions sur des plats spécifiques, des ingrédients, des techniques de cuisine, des traditions alimentaires culturelles ou de l'aide pour naviguer dans notre menu et passer des commandes. Qu'aimeriez-vous savoir ?";
    } else {
      return "Merci pour votre intérêt pour la cuisine allemande ! Je serais heureux de vous en dire plus sur des plats spécifiques, des ingrédients, des spécialités régionales ou des méthodes de cuisson. Vous pouvez également poser des questions sur notre menu, notre processus de commande ou nos traditions alimentaires culturelles. Y a-t-il quelque chose de spécifique sur la culture alimentaire allemande que vous aimeriez explorer ?";
    }
  }
}
