import React, { createContext, useState, useContext, useEffect } from 'react';
import { Language } from '@/types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const defaultLanguage: Language = 'en';

// This would normally come from a translation file or API
const translations: Record<Language, Record<string, string>> = {
  en: {
    'site.title': 'Guten Eats: German Culinary Tour',
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.about': 'About',
    'nav.cart': 'Cart',
    'nav.team': 'Team',
    'hero.title': 'Experience Authentic German Cuisine',
    'hero.subtitle': 'From the Black Forest to Bavaria, discover the rich flavors of Germany',
    'hero.cta': 'Take the GutenEats Tour',
    'dishes.title': 'Traditional German Dishes',
    'dishes.subtitle': 'Authentic recipes from across Germany',
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.checkout': 'Proceed to Checkout',
    'checkout.title': 'Checkout',
    'checkout.name': 'Full Name',
    'checkout.email': 'Email',
    'checkout.address': 'Delivery Address',
    'checkout.submit': 'Place Order',
    'about.title': 'About German Cuisine',
    'about.subtitle': 'A culinary journey through history and tradition',
    'about.sustainable.title': 'Our Sustainable Goals',
    'about.sustainable.description': 'At GutenEats, we\'re committed to sustainable practices that support both people and the planet.',
    'about.heritage.title': 'The Rich Heritage of German Cuisine',
    'about.heritage.intro': 'German cuisine varies from region to region, reflecting the country\'s federal history. Each region has its own distinctive culinary traditions, often reflecting the local economy, cultural history, and geography.',
    'about.heritage.southern': 'Southern Germany, especially Bavaria and Swabia, is known for hearty dishes featuring dumplings, potatoes, and meat, particularly pork. The influence of neighboring Austria and Switzerland is evident in dishes like Schnitzel and Spätzle.',
    'about.regional.title': 'Regional Diversity',
    'about.regional.northern': 'Northern German cuisine, influenced by Scandinavian cuisine, features seafood, especially herring, as evidenced by dishes like Labskaus and Finkenwerder Scholle. Eastern German cuisine shows the influence of Slavic countries and is known for its hearty flavors, with dishes like Soljanka and Sauerbraten.',
    'about.regional.western': 'Western German cuisine, especially in the Rhineland, has been influenced by French cuisine, particularly evident in the use of wine in cooking and the fondness for white asparagus. The use of herbs and spices like juniper berries, caraway, and lovage is characteristic of central German cuisine.',
    'about.audio.play': 'Play Audio Guide',
    'about.audio.pause': 'Pause Audio Guide',
    'about.staples.title': 'Bread & Beer: Cultural Staples',
    'about.staples.content': 'Bread plays an important role in German cuisine, with more than 300 basic varieties and 1,200 different types of pastries and rolls. Germans consume about 80 kg of bread per person each year. Beer is also central to German culture, with the country\'s Beer Purity Law (Reinheitsgebot) dating back to 1516, ensuring the quality and purity of German beer.',
    'about.seasonal.title': 'Seasonal Celebrations',
    'about.seasonal.content': 'German cuisine is closely tied to seasonal celebrations. Oktoberfest, the world\'s largest beer festival, features special dishes like Hendl (roast chicken), Schweinebraten (roast pork), and Würstl (sausages). Christmas markets offer seasonal treats like Lebkuchen (gingerbread), Stollen (fruit bread), and Glühwein (mulled wine).',
    'about.gallery.title': 'Visual Journey Through German Cuisine',
    'chatbot.placeholder': 'Ask about German cuisine...',
    'chatbot.greeting': 'Hello! I\'m Guten Chef, your German cuisine assistant. Ask me about dishes, recipes, ingredients, or placing an order. I can also tell you about cultural food traditions!',
    'chatbot.voiceNotSupported': 'Voice Recognition Not Supported',
    'chatbot.voiceNotSupportedDesc': 'Your browser does not support voice recognition. Please type your question.',
    'chatbot.voiceError': 'Voice Recognition Error',
    'chatbot.listeningStarted': 'Listening',
    'chatbot.speakNow': 'Please speak now...',
    'chatbot.listening': 'Listening...',
    'chatbot.speakerEnabled': 'Voice responses enabled',
    'chatbot.speakerDisabled': 'Voice responses disabled',
    'chatbot.microphoneError': 'Microphone error. Please try again.',
    'chatbot.microphonePermissionError': 'Please allow microphone access to use voice input.',
    'chatbot.welcome': 'Hello! I\'m Guten Chef, your virtual guide to German cuisine. How can I enhance your culinary journey today? Ask me about dishes, ingredients, cooking techniques, or place an order!',
    'chatbot.title': 'Guten Chef Assistant',
    'chatbot.open': 'Open chat assistant',
    'chatbot.micOn': 'Turn on microphone',
    'chatbot.micOff': 'Turn off microphone',
    'chatbot.send': 'Send message',
    'footer.rights': 'All Rights Reserved',
    'language': 'Language',
    'back.to.menu': 'Back to Menu',
    'recipe.read.aloud': 'Read Recipe Aloud',
    'recipe.stop.reading': 'Stop Reading',
    'recipe.ingredients': 'Ingredients',
    'recipe.preparation': 'Preparation steps',
    'recipe.voice.error': 'Voice Synthesis Error',
    'recipe.voice.error.description': 'There was an error with the voice synthesis. Please try again.',
    'members.title': 'Meet the GutenEats Gang 🥨🍺',
    'members.member': 'Member',
    'members.faculty.title': 'Faculty Guide',
    'members.faculty.bio': 'With over 8 years of experience, Mrs. Bhuvana Udhayakumar teaches in the Department of English and Foreign Languages at the Faculty of Engineering & Technology, Kattankulathur Campus, Chennai. Her academic and research interests include English Literature, Feminism, Cultural Studies, Women\'s Studies, and Eco-Feminism. She also teaches German, fostering cross-cultural communication and empowering students with both linguistic and literary insights.',
    'members.faculty.quote': 'The sauerkraut to our schnitzel – giving flavor and balance to everything we do! 🥬✨',
    'sdg.badge': 'UN Sustainable Goal',
    'sdg.title': 'ZERO HUNGER',
    'sdg.description': 'Promoting Zero Hunger through the power of traditional German cuisine. Our project not only shares recipes but raises awareness about food accessibility, sustainable food practices, and cultural appreciation.',
    'sdg.feature1.title': 'Reducing Food Waste',
    'sdg.feature1.description': 'Our recipes include creative ways to use every part of ingredients and preserve seasonal foods.',
    'sdg.feature2.title': 'Equitable Food Access',
    'sdg.feature2.description': 'We promote recipes that are nutritious, affordable, and accessible to all communities.',
    'sdg.feature3.title': 'Cultural Preservation',
    'sdg.feature3.description': 'Preserving culinary traditions helps maintain food knowledge across generations.',
    'sdg.button': 'Learn More About Zero Hunger',
    'cultural.title': 'Uniqueness of GutenEats',
    'cultural.subtitle': 'Flavor. Heritage. Simplicity.',
    'cultural.feature1.title': 'Authentic Recipes',
    'cultural.feature1.description': 'Our dishes follow time-honored German recipes passed down through generations.',
    'cultural.feature2.title': 'Fresh Ingredients',
    'cultural.feature2.description': 'We use only the freshest, locally-sourced ingredients for all our German specialties.',
    'cultural.feature3.title': 'Cultural Experience',
    'cultural.feature3.description': 'Each dish comes with cultural context and audio pronunciation in multiple languages.',
    'cultural.feature4.title': 'Regional Varieties',
    'cultural.feature4.description': 'Explore the diverse culinary traditions from different German regions.',
    'about.farm.title': 'Farm to Table',
    'about.farm.subtitle': 'Supporting local farmers and reducing food miles',
    'about.farm.description': 'We source 80% of our ingredients from local farms within a 100km radius, reducing carbon emissions while supporting regional economies.',
    'about.waste.title': 'Reducing Waste',
    'about.waste.subtitle': 'Minimizing our environmental footprint',
    'about.waste.description': 'Through composting, recycling, and mindful preparation, we\'ve reduced our food waste by 65% since 2020, working toward zero waste by 2026.',
    'about.culture.title': 'Cultural Preservation',
    'about.culture.subtitle': 'Honoring traditional methods and recipes',
    'about.culture.description': 'We preserve authentic German culinary traditions while adapting them for contemporary, sustainable cooking practices.',
    'about.hunger.title': 'ZERO HUNGER',
    'about.hunger.description': 'We\'re proudly contributing to the United Nations\' Sustainable Development Goal #2: Zero Hunger.',
    'about.hunger.commitment.title': 'Our Commitment to Food Security',
    'about.hunger.commitment.description': 'GutenEats has partnered with local food banks to donate over 10,000 meals annually. We believe that access to nutritious food is a fundamental right for everyone.',
    'about.hunger.initiatives': 'Our Zero Hunger Initiatives',
    'about.hunger.initiative1': 'Weekly meal donations to community shelters',
    'about.hunger.initiative2': 'Training programs for sustainable agriculture',
    'about.hunger.initiative3': 'Educational workshops on reducing food waste',
    'about.hunger.initiative4': 'Support for small-scale local farmers',
    'about.hunger.initiative5': 'Community gardens in urban food deserts',
    'about.impact.title': 'Impact Statistics',
    'about.impact.meals': 'Meals donated annually',
    'about.impact.gardens': 'Community gardens supported',
    'about.impact.hours': 'Volunteer hours monthly',
    'about.impact.farmers': 'Local farmers supported',
    'chatbot.speechNotSupported': 'Speech recognition is not supported in your browser',
    'chatbot.noSpeechDetected': 'No speech detected',
    'chatbot.pleaseSpeakClearly': 'Try speaking more clearly or in a quieter environment',
    'chatbot.microphonePermissionDenied': 'Microphone permission denied',
    'chatbot.speechError': 'Speech recognition error',
    'chatbot.startListeningError': 'Could not start listening',
    'chatbot.speechSetupError': 'Could not set up speech recognition',
    'chatbot.lowConfidence': 'Speech recognition uncertainty',
    'chatbot.pleaseReviewBeforeSubmitting': 'Please review the text before sending',
    'menu.title': 'German Culinary Experience',
    'menu.subtitle': 'Explore the rich flavors of German cuisine, from hearty meat dishes to delicious desserts. All our recipes are authentic and prepared with traditional methods.',
    'menu.searchPlaceholder': 'Search dishes, ingredients, or regions...',
    'menu.sort': 'Sort',
    'menu.dish': 'dish',
    'menu.dishes': 'dishes',
    'menu.found': 'found',
    'menu.in': 'in',
    'menu.matching': 'matching',
    'category.all': 'All Dishes',
    'category.sausages': 'Sausages',
    'category.meat': 'Meat Dishes',
    'category.sides': 'Sides',
    'category.desserts': 'Desserts',
    'home.viewAllDishes': 'View All Dishes',
    'footer.tagline': 'Authentic German cuisine delivered to your table. Explore the rich culinary traditions of Germany.',
    'footer.navigation': 'Navigation',
    'footer.cookedBy': 'Cooked up with ❤️ by Kabilesh C',
    'cart.itemsLabel': 'Items',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Delivery',
    'cart.total': 'Total',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.delivery': 'Delivery',
    'checkout.total': 'Total',
    'checkout.confirmationTitle': 'Order Confirmed!',
    'checkout.confirmationMessage': "Thank you for your order. We've sent a confirmation email to {email}.",
    'checkout.orderNumberMessage': 'Your order number is: {orderNumber}',
    'checkout.returnHome': 'Return to Home',
    'button.viewRecipe': 'View Recipe',
    'button.addToCart': 'Add to Cart',
    'cart.browseMenu': 'Browse Menu',
  },
  de: {
    'site.title': 'Guten Eats: Deutsche Kulinarische Tour',
    'nav.home': 'Startseite',
    'nav.menu': 'Speisekarte',
    'nav.about': 'Über Uns',
    'nav.cart': 'Warenkorb',
    'nav.team': 'Team',
    'hero.title': 'Erleben Sie Authentische Deutsche Küche',
    'hero.subtitle': 'Vom Schwarzwald bis Bayern, entdecken Sie die reichhaltigen Aromen Deutschlands',
    'hero.cta': 'Entdecken Sie Unsere Gerichte',
    'dishes.title': 'Traditionelle Deutsche Gerichte',
    'dishes.subtitle': 'Authentische Rezepte aus ganz Deutschland',
    'cart.title': 'Ihr Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.checkout': 'Zur Kasse',
    'checkout.title': 'Kasse',
    'checkout.name': 'Vollständiger Name',
    'checkout.email': 'E-Mail',
    'checkout.address': 'Lieferadresse',
    'checkout.submit': 'Bestellung aufgeben',
    'about.title': 'Über Deutsche Küche',
    'about.subtitle': 'Eine kulinarische Reise durch Geschichte und Tradition',
    'about.sustainable.title': 'Unsere Nachhaltigkeitsziele',
    'about.sustainable.description': 'Bei GutenEats setzen wir uns für nachhaltige Praktiken ein, die sowohl Menschen als auch den Planeten unterstützen.',
    'about.heritage.title': 'Das reiche Erbe der deutschen Küche',
    'about.heritage.intro': 'Die deutsche Küche variiert von Region zu Region und spiegelt die föderale Geschichte des Landes wider. Jede Region hat ihre eigenen charakteristischen kulinarischen Traditionen, die oft die lokale Wirtschaft, Kulturgeschichte und Geographie widerspiegeln.',
    'about.heritage.southern': 'Süddeutschland, insbesondere Bayern und Schwaben, ist bekannt für herzhafte Gerichte mit Knödeln, Kartoffeln und Fleisch, besonders Schweinefleisch. Der Einfluss der Nachbarländer Österreich und Schweiz zeigt sich in Gerichten wie Schnitzel und Spätzle.',
    'about.regional.title': 'Regionale Vielfalt',
    'about.regional.northern': 'Die norddeutsche Küche, beeinflusst von der skandinavischen Küche, bietet Meeresfrüchte, insbesondere Hering, wie Gerichte wie Labskaus und Finkenwerder Scholle zeigen. Die ostdeutsche Küche zeigt den Einfluss slawischer Länder und ist bekannt für ihre herzhaften Aromen, mit Gerichten wie Soljanka und Sauerbraten.',
    'about.regional.western': 'Die westdeutsche Küche, besonders im Rheinland, wurde von der französischen Küche beeinflusst, was besonders in der Verwendung von Wein beim Kochen und der Vorliebe für weißen Spargel deutlich wird. Die Verwendung von Kräutern und Gewürzen wie Wacholderbeeren, Kümmel und Liebstöckel ist charakteristisch für die mitteldeutsche Küche.',
    'about.audio.play': 'Audio-Guide abspielen',
    'about.audio.pause': 'Audio-Guide pausieren',
    'about.staples.title': 'Brot & Bier: Kulturelle Grundnahrungsmittel',
    'about.staples.content': 'Brot spielt eine wichtige Rolle in der deutschen Küche, mit mehr als 300 Grundsorten und 1.200 verschiedenen Arten von Gebäck und Brötchen. Deutsche konsumieren etwa 80 kg Brot pro Person jährlich. Bier ist auch zentral für die deutsche Kultur, wobei das Reinheitsgebot des Landes aus dem Jahr 1516 stammt und die Qualität und Reinheit des deutschen Bieres sicherstellt.',
    'about.seasonal.title': 'Saisonale Feiern',
    'about.seasonal.content': 'Die deutsche Küche ist eng mit saisonalen Feiern verbunden. Das Oktoberfest, das größte Bierfest der Welt, bietet besondere Gerichte wie Hendl (Brathähnchen), Schweinebraten und Würstl. Weihnachtsmärkte bieten saisonale Leckereien wie Lebkuchen, Stollen und Glühwein.',
    'about.gallery.title': 'Visuelle Reise durch die deutsche Küche',
    'chatbot.placeholder': 'Fragen Sie über deutsche Küche...',
    'chatbot.greeting': 'Hallo! Ich bin Guten Chef, Ihr Assistent für deutsche Küche. Fragen Sie mich nach Gerichten, Rezepten, Zutaten oder wie Sie eine Bestellung aufgeben können. Ich kann Ihnen auch etwas über kulturelle Essenstraditionen erzählen!',
    'chatbot.voiceNotSupported': 'Spracherkennung Nicht Unterstützt',
    'chatbot.voiceNotSupportedDesc': 'Ihr Browser unterstützt keine Spracherkennung. Bitte tippen Sie Ihre Frage ein.',
    'chatbot.voiceError': 'Spracherkennungsfehler',
    'chatbot.listeningStarted': 'Höre zu',
    'chatbot.speakNow': 'Bitte sprechen Sie jetzt...',
    'chatbot.listening': 'Ich höre zu...',
    'chatbot.speakerEnabled': 'Sprachantworten aktiviert',
    'chatbot.speakerDisabled': 'Sprachantworten deaktiviert',
    'chatbot.microphoneError': 'Mikrofonfehler. Bitte versuchen Sie es erneut.',
    'chatbot.microphonePermissionError': 'Bitte erlauben Sie den Mikrofonzugriff, um die Spracheingabe zu nutzen.',
    'chatbot.welcome': 'Hallo! Ich bin Guten Chef, Ihr virtueller Führer durch die deutsche Küche. Wie kann ich Ihre kulinarische Reise heute bereichern? Fragen Sie mich nach Gerichten, Zutaten, Kochtechniken oder geben Sie eine Bestellung auf!',
    'chatbot.title': 'Guten Chef Assistent',
    'chatbot.open': 'Chat-Assistent öffnen',
    'chatbot.micOn': 'Mikrofon einschalten',
    'chatbot.micOff': 'Mikrofon ausschalten',
    'chatbot.send': 'Nachricht senden',
    'footer.rights': 'Alle Rechte Vorbehalten',
    'language': 'Sprache',
    'back.to.menu': 'Zurück zur Speisekarte',
    'recipe.read.aloud': 'Rezept Vorlesen',
    'recipe.stop.reading': 'Vorlesen Beenden',
    'recipe.ingredients': 'Zutaten',
    'recipe.preparation': 'Zubereitungsschritte',
    'recipe.voice.error': 'Sprachsynthese-Fehler',
    'recipe.voice.error.description': 'Bei der Sprachsynthese ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    'members.title': 'Treffen Sie die GutenEats Gang 🥨🍺',
    'members.member': 'Mitglied',
    'members.faculty.title': 'Fakultätsleitung',
    'members.faculty.bio': 'Mit über 8 Jahren Erfahrung unrichtet Frau Bhuvana Udhayakumar in der Abteilung für Englisch und Fremdsprachen an der Fakultät für Ingenieurwissenschaften und Technologie, Campus Kattankulathur, Chennai. Ihre akademischen und Forschungsinteressen umfassen Englische Literatur, Feminismus, Kulturwissenschaften, Frauenstudien und Öko-Feminismus. Sie unterrichtet auch Deutsch und fördert die interkulturelle Kommunikation und stärkt Studierende mit sprachlichen und literarischen Einsichten.',
    'members.faculty.quote': 'Das Sauerkraut zu unserem Schnitzel – gibt allem, was wir tun, Geschmack und Balance! 🥬✨',
    'sdg.badge': 'UN-Nachhaltigkeitsziel',
    'sdg.title': 'KEIN HUNGER',
    'sdg.description': 'Förderung von Null Hunger durch die Kraft der traditionellen deutschen Küche. Unser Projekt teilt nicht nur Rezepte, sondern schärft das Bewusstsein für Nahrungsmittelzugänglichkeit, nachhaltige Nahrungsmittelpraktiken und kulturelle Wertschätzung.',
    'sdg.feature1.title': 'Reduzierung von Lebensmittelabfällen',
    'sdg.feature1.description': 'Unsere Rezepte beinhalten kreative Möglichkeiten, jeden Teil der Zutaten zu verwenden und saisonale Lebensmittel zu konservieren.',
    'sdg.feature2.title': 'Gerechter Zugang zu Lebensmitteln',
    'sdg.feature2.description': 'Wir fördern Rezepte, die nahrhaft, erschwinglich und für alle Gemeinschaften zugänglich sind.',
    'sdg.feature3.title': 'Kulturelle Bewahrung',
    'sdg.feature3.description': 'Preserving culinary traditions helps maintain food knowledge across generations.',
    'sdg.button': 'Mehr über Null Hunger erfahren',
    'cultural.title': 'Einzigartigkeit von GutenEats',
    'cultural.subtitle': 'Geschmack. Erbe. Einfachheit.',
    'cultural.feature1.title': 'Authentische Rezepte',
    'cultural.feature1.description': 'Unsere Gerichte folgen altehrwürdigen deutschen Rezepten, die über Generationen weitergegeben wurden.',
    'cultural.feature2.title': 'Frische Zutaten',
    'cultural.feature2.description': 'Wir verwenden nur die frischesten, lokal bezogenen Zutaten für alle unsere deutschen Spezialitäten.',
    'cultural.feature3.title': 'Kulturelles Erlebnis',
    'cultural.feature3.description': 'Jedes Gericht kommt mit kulturellem Kontext und Audioaussprache in mehreren Sprachen.',
    'cultural.feature4.title': 'Regionale Vielfalt',
    'cultural.feature4.description': 'Entdecken Sie die vielfältigen kulinarischen Traditionen aus verschiedenen deutschen Regionen.',
    'about.farm.title': 'Vom Bauernhof auf den Tisch',
    'about.farm.subtitle': 'Unterstützung lokaler Landwirte und Reduzierung der Lebensmittelmeilen',
    'about.farm.description': 'Wir beziehen 80% unserer Zutaten von lokalen Bauernhöfen in einem Umkreis von 100 km, reduzieren Kohlenstoffemissionen und unterstützen regionale Wirtschaften.',
    'about.waste.title': 'Abfallreduzierung',
    'about.waste.subtitle': 'Minimierung unseres ökologischen Fußabdrucks',
    'about.waste.description': 'Durch Kompostierung, Recycling und bewusste Zubereitung haben wir unsere Lebensmittelabfälle seit 2020 um 65% reduziert und arbeiten auf Null-Abfall bis 2026 hin.',
    'about.culture.title': 'Cultural Preservation',
    'about.culture.subtitle': 'Honoring traditional methods and recipes',
    'about.culture.description': 'We preserve authentic German culinary traditions while adapting them for contemporary, sustainable cooking practices.',
    'about.hunger.title': 'KEIN HUNGER',
    'about.hunger.description': 'Wir leisten stolz einen Beitrag zum Ziel für nachhaltige Entwicklung Nr. 2 der Vereinten Nationen: Kein Hunger.',
    'about.hunger.commitment.title': 'Unser Engagement für Ernährungssicherheit',
    'about.hunger.commitment.description': 'GutenEats hat sich mit lokalen Lebensmittelbanken zusammengetan, um jährlich über 10,000 Mahlzeiten zu spenden. Wir glauben, dass der Zugang zu nahrhaften Lebensmitteln ein grundlegendes Recht für jeden ist.',
    'about.hunger.initiatives': 'Unsere Null-Hunger-Initiativen',
    'about.hunger.initiative1': 'Wöchentliche Mahlzeitenspenden an Gemeinschaftsunterkünfte',
    'about.hunger.initiative2': 'Training programs for sustainable agriculture',
    'about.hunger.initiative3': 'Educational workshops on reducing food waste',
    'about.hunger.initiative4': 'Support for small-scale local farmers',
    'about.hunger.initiative5': 'Community gardens in urban food deserts',
    'about.impact.title': 'Wirkungsstatistiken',
    'about.impact.meals': 'Jährlich gespendete Mahlzeiten',
    'about.impact.gardens': 'Unterstützte Gemeinschaftsgärten',
    'about.impact.hours': 'Freiwilligenstunden monatlich',
    'about.impact.farmers': 'Unterstützte lokale Landwirte',
    'chatbot.speechNotSupported': 'Spracherkennung wird in Ihrem Browser nicht unterstützt',
    'chatbot.noSpeechDetected': 'Keine Sprache erkannt',
    'chatbot.pleaseSpeakClearly': 'Versuchen Sie, deutlicher zu sprechen oder in einer ruhigeren Umgebung',
    'chatbot.microphonePermissionDenied': 'Mikrofonzugriff verweigert',
    'chatbot.speechError': 'Spracherkennungsfehler',
    'chatbot.startListeningError': 'Konnte Spracherkennung nicht starten',
    'chatbot.speechSetupError': 'Konnte Spracherkennung nicht einrichten',
    'chatbot.lowConfidence': 'Spracherkennung unsicher',
    'chatbot.pleaseReviewBeforeSubmitting': 'Bitte überprüfen Sie den Text vor dem Senden',
    'menu.title': 'Deutsche Kulinarische Erfahrung',
    'menu.subtitle': 'Entdecken Sie die reichhaltigen Aromen der deutschen Küche, von herzhaften Fleischgerichten bis hin zu köstlichen Desserts. Alle unsere Rezepte sind authentisch und werden nach traditionellen Methoden zubereitet.',
    'menu.searchPlaceholder': 'Gerichte, Zutaten oder Regionen suchen...',
    'menu.sort': 'Sortieren',
    'menu.dish': 'Gericht',
    'menu.dishes': 'Gerichte',
    'menu.found': 'gefunden',
    'menu.in': 'in',
    'menu.matching': 'übereinstimmend',
    'category.all': 'Alle Gerichte',
    'category.sausages': 'Würstchen',
    'category.meat': 'Fleischgerichte',
    'category.sides': 'Beilagen',
    'category.desserts': 'Desserts',
    'home.viewAllDishes': 'Alle Gerichte Anzeigen',
    'footer.tagline': 'Authentische deutsche Küche direkt an Ihren Tisch. Entdecken Sie die reichen kulinarischen Traditionen Deutschlands.',
    'footer.navigation': 'Navigation',
    'footer.cookedBy': 'Mit ❤️ gekocht von Kabilesh C',
    'cart.itemsLabel': 'Artikel',
    'cart.orderSummary': 'Bestellübersicht',
    'cart.subtotal': 'Zwischensumme',
    'cart.delivery': 'Lieferung',
    'cart.total': 'Gesamt',
    'checkout.orderSummary': 'Bestellübersicht',
    'checkout.subtotal': 'Zwischensumme',
    'checkout.delivery': 'Lieferung',
    'checkout.total': 'Gesamt',
    'checkout.confirmationTitle': 'Bestellung Bestätigt!',
    'checkout.confirmationMessage': "Vielen Dank für Ihre Bestellung. Wir haben eine Bestätigungs-E-Mail an {email} gesendet.",
    'checkout.orderNumberMessage': 'Ihre Bestellnummer lautet: {orderNumber}',
    'checkout.returnHome': 'Zurück zur Startseite',
    'button.viewRecipe': 'Rezept anzeigen',
    'button.addToCart': 'Zum Warenkorb hinzufügen',
    'cart.browseMenu': 'Speisekarte durchsuchen',
  },
  es: {
    'site.title': 'Guten Eats: Tour Culinario Alemán',
    'nav.home': 'Inicio',
    'nav.menu': 'Menú',
    'nav.about': 'Acerca de',
    'nav.cart': 'Carrito',
    'nav.team': 'Equipo',
    'hero.title': 'Experimente la Auténtica Cocina Alemana',
    'hero.subtitle': 'Desde la Selva Negra hasta Baviera, descubra los ricos sabores de Alemania',
    'hero.cta': 'Take the GutenEats Tour',
    'dishes.title': 'Platos Tradicionales Alemanes',
    'dishes.subtitle': 'Recetas auténticas de toda Alemania',
    'cart.title': 'Su Carrito',
    'cart.empty': 'Su carrito está vacío',
    'cart.checkout': 'Proceder al Pago',
    'checkout.title': 'Pago',
    'checkout.name': 'Nombre Completo',
    'checkout.email': 'Correo Electrónico',
    'checkout.address': 'Dirección de Entrega',
    'checkout.submit': 'Realizar Pedido',
    'about.title': 'Sobre la Cocina Alemana',
    'about.subtitle': 'Un viaje culinario a través de la historia y la tradición',
    'about.sustainable.title': 'Nuestros Objetivos Sostenibles',
    'about.sustainable.description': 'En GutenEats, estamos comprometidos con prácticas sostenibles que apoyan tanto a las personas como al planeta.',
    'about.heritage.title': 'El Rico Patrimonio de la Cocina Alemana',
    'about.heritage.intro': 'La cocina alemana varía de región a región, reflejando la historia federal del país. Cada región tiene sus propias tradiciones culinarias distintivas, que a menudo reflejan la economía local, la historia cultural y la geografía.',
    'about.heritage.southern': 'El sur de Alemania, especialmente Baviera y Suabia, es conocido por sus platos contundentes con albóndigas, patatas y carne, particularmente cerdo. La influencia de los países vecinos Austria y Suiza es evidente en platos como Schnitzel y Spätzle.',
    'about.regional.title': 'Diversidad Regional',
    'about.regional.northern': 'La cocina del norte de Alemania, influenciada por la cocina escandinava, presenta mariscos, especialmente arenque, como lo demuestran platos como Labskaus y Finkenwerder Scholle. La cocina de l\'est de l\'Allemagne montre l\'influence des pays slaves y es conocida por sus sabores contundentes, con platos como la Soljanka y el Sauerbraten.',
    'about.regional.western': 'La cocina del oeste de Alemania, especialmente en Renania, ha sido influenciada por la cocina francesa, particularmente evidente en el uso del vino en la cocina y la predilección por los espárragos blancos. El uso de hierbas y especias como bayas de enebro, alcaravea y levístico es característico de la cocina del centro de Alemania.',
    'about.audio.play': 'Reproducir Guía de Audio',
    'about.audio.pause': 'Pausar Guía de Audio',
    'about.staples.title': 'Pan y Cerveza: Elementos Básicos Culturales',
    'about.staples.content': 'El pan juega un papel importante en la cocina alemana, con más de 300 variedades básicas y 1.200 tipos diferentes de pasteles y panecillos. Los alemanes consumen aproximadamente 80 kg de pan por persona cada año. La cerveza también es central para la cultura alemana, con la Ley de Pureza de la Cerveza (Reinheitsgebot) que data de 1516, asegurando la calidad y pureza de la cerveza alemana.',
    'about.seasonal.title': 'Celebraciones Estacionales',
    'about.seasonal.content': 'La cocina alemana está estrechamente vinculada a las celebraciones estacionales. El Oktoberfest, el festival de cerveza más grande del mundo, presenta platos especiales como Hendl (pollo asado), Schweinebraten (cerdo asado) y Würstl (salchichas). Los mercados navideños ofrecen golosinas de temporada como Lebkuchen (pan de jengibre), Stollen (pan de frutas) y Glühwein (vino caliente).',
    'about.gallery.title': 'Viaje Visual por la Cocina Alemana',
    'chatbot.placeholder': 'Pregunte sobre la cocina alemana...',
    'chatbot.greeting': '¡Hola! Soy Guten Chef, su asistente de cocina alemana. Pregúnteme sobre platos, recetas, ingredientes o cómo realizar un pedido. ¡También puedo contarle sobre las tradiciones culinarias culturales!',
    'chatbot.voiceNotSupported': 'Reconocimiento de Voz No Compatible',
    'chatbot.voiceNotSupportedDesc': 'Su navegador no admite el reconocimiento de voz. Por favor, escriba su pregunta.',
    'chatbot.voiceError': 'Error de Reconocimiento de Voz',
    'chatbot.listeningStarted': 'Escuchando',
    'chatbot.speakNow': 'Por favor, hable ahora...',
    'chatbot.listening': 'Escuchando...',
    'chatbot.speakerEnabled': 'Respuestas de voz activadas',
    'chatbot.speakerDisabled': 'Respuestas de voz desactivadas',
    'chatbot.microphoneError': 'Error de micrófono. Por favor, inténtelo de nuevo.',
    'chatbot.microphonePermissionError': 'Por favor, permita el acceso al micrófono para usar la entrada de voz.',
    'chatbot.welcome': '¡Hola! Soy Guten Chef, su guía virtual de la cocina alemana. ¿Cómo puedo enriquecer su viaje culinario hoy? ¡Pregúnteme sobre platos, ingredientes, técnicas de cocina o haga un pedido!',
    'chatbot.title': 'Asistente Guten Chef',
    'chatbot.open': 'Abrir asistente de chat',
    'chatbot.micOn': 'Activar micrófono',
    'chatbot.micOff': 'Desactivar micrófono',
    'chatbot.send': 'Enviar mensaje',
    'footer.rights': 'Todos los Derechos Reservados',
    'language': 'Idioma',
    'back.to.menu': 'Volver al Menú',
    'recipe.read.aloud': 'Leer Receta en Voz Alta',
    'recipe.stop.reading': 'Detener Lectura',
    'recipe.ingredients': 'Ingredientes',
    'recipe.preparation': 'Pasos de preparación',
    'recipe.voice.error': 'Error de Síntesis de Voz',
    'recipe.voice.error.description': 'Hubo un error con la síntesis de voz. Por favor, inténtelo de nuevo.',
    'members.title': 'Conoce a la Pandilla GutenEats 🥨🍺',
    'members.member': 'Miembro',
    'members.faculty.title': 'Guía Docente',
    'members.faculty.bio': 'Con más de 8 años de experiencia, la Sra. Bhuvana Udhayakumar enseña en el Departamento de Inglés y Lenguas Extranjeras en la Facultad de Ingeniería y Tecnología, Campus Kattankulathur, Chennai. Sus intereses académicos y de investigación incluyen Literatura Inglesa, Feminismo, Estudios Culturales, Estudios de la Mujer y Eco-Feminismo. También enseña alemán, fomentando la comunicación intercultural y empoderando a los estudiantes con conocimientos lingüísticos y literarios.',
    'members.faculty.quote': '¡El chucrut para nuestro schnitzel – dando sabor y equilibrio a todo lo que hacemos! 🥬✨',
    'sdg.badge': 'Objetivo Sostenible de la ONU',
    'sdg.title': 'HAMBRE CERO',
    'sdg.description': 'Promoviendo Hambre Cero a través del poder de la cocina tradicional alemana. Nuestro proyecto no solo comparte recetas sino que crea conciencia sobre la accesibilidad a los alimentos, prácticas alimentarias sostenibles y apreciación cultural.',
    'sdg.feature1.title': 'Reducción del Desperdicio de Alimentos',
    'sdg.feature1.description': 'Nuestras recetas incluyen formas creativas de usar cada parte de los ingredientes y preservar alimentos de temporada.',
    'sdg.feature2.title': 'Acceso Equitativo a Alimentos',
    'sdg.feature2.description': 'Promovemos recetas que son nutritivas, asequibles y accesibles para todas las comunidades.',
    'sdg.feature3.title': 'Preservación Cultural',
    'sdg.feature3.description': 'Préserver les traditions culinaires aide à maintenir les connaissances alimentaires à travers les générations.',
    'sdg.button': 'Más Información Sobre Hambre Cero',
    'cultural.title': 'Singularidad de GutenEats',
    'cultural.subtitle': 'Sabor. Patrimonio. Simplicidad.',
    'cultural.feature1.title': 'Recetas Auténticas',
    'cultural.feature1.description': 'Nuestros platos siguen recetas alemanas tradicionales transmises de génération en génération.',
    'cultural.feature2.title': 'Ingredientes Frescos',
    'cultural.feature2.description': 'Utilizamos solo los ingredientes más frescos y de origen local para todas nuestras especialidades alemanas.',
    'cultural.feature3.title': 'Experiencia Cultural',
    'cultural.feature3.description': 'Cada plato viene con contexto cultural y pronunciación de audio en varios idiomas.',
    'cultural.feature4.title': 'Variedades Regionales',
    'cultural.feature4.description': 'Explore las diversas tradiciones culinarias de diferentes regiones alemanas.',
    'about.farm.title': 'De la Granja a la Mesa',
    'about.farm.subtitle': 'Apoyando a agricultores locales y reduciendo millas alimentarias',
    'about.farm.description': 'Obtenemos el 80% de nuestros ingredientes de granjas locales en un radio de 100km, reduciendo emisiones de carbono mientras apoyamos economías regionales.',
    'about.waste.title': 'Reducción de Residuos',
    'about.waste.subtitle': 'Minimizando nuestra huella ambiental',
    'about.waste.description': 'Grâce au compostage, au recyclage et à une préparation consciente, nous avons réduit nos déchets alimentaires de 65% depuis 2020, travaillant vers zéro déchet d\'ici 2026.',
    'about.culture.title': 'Préservation Culturelle',
    'about.culture.subtitle': 'Honorer les méthodes et recettes traditionnelles',
    'about.culture.description': 'Nous préservons les traditions culinaires allemandes authentiques tout en les adaptant aux pratiques de cuisine contemporaines et durables.',
    'about.hunger.title': 'HAMBRE CERO',
    'about.hunger.description': 'Estamos orgullosamente contribuyendo al Objetif de Développement Durable n°2 des Nations Unies : Faim Zéro.',
    'about.hunger.commitment.title': 'Nuestro Compromiso con la Seguridad Alimentaire',
    'about.hunger.commitment.description': 'GutenEats se ha asociado con bancos de alimentos locales para donar más de 10,000 comidas por año. Creemos que el acceso a alimentos nutritivos es un derecho fundamental para todos.',
    'about.hunger.initiatives': 'Nuestras Iniciativas de Hambre Cero',
    'about.hunger.initiative1': 'Donaciones semanales de comidas a refugios comunitarios',
    'about.hunger.initiative2': 'Programmes de formation à l\'agriculture durable',
    'about.hunger.initiative3': 'Ateliers éducatifs sur la réduction du gaspillage alimentaire',
    'about.hunger.initiative4': 'Soutien aux petits agriculteurs locaux',
    'about.hunger.initiative5': 'Jardins communautaires dans les déserts alimentaires urbains',
    'about.impact.title': 'Estadísticas de Impacto',
    'about.impact.meals': 'Comidas donadas anualmente',
    'about.impact.gardens': 'Huertos comunitarios apoyados',
    'about.impact.hours': 'Horas de bénévolat mensuelles',
    'about.impact.farmers': 'Agricultores locales apoyados',
    'chatbot.speechNotSupported': 'El reconocimiento de voz no es compatible con su navegador',
    'chatbot.noSpeechDetected': 'No se detectó voz',
    'chatbot.pleaseSpeakClearly': 'Intente hablar más claramente o en un ambiente más silencioso',
    'chatbot.microphonePermissionDenied': 'Permiso de micrófono denegado',
    'chatbot.speechError': 'Erreur de reconnaissance vocale',
    'chatbot.startListeningError': 'No se pudo comenzar l\'écoute',
    'chatbot.speechSetupError': 'No se pudo configurar la reconnaissance vocale',
    'chatbot.lowConfidence': 'Incertidumbre en el reconocimiento de voz',
    'chatbot.pleaseReviewBeforeSubmitting': 'Por favor, revise el texto antes de enviar',
    'menu.title': 'Experiencia Gastronómica Alemana',
    'menu.subtitle': 'Explore los ricos sabores de la cocina alemana, desde contundentes platos de carne hasta deliciosos postres. Todas nuestras recetas son auténticas y se preparan con métodos tradicionales.',
    'menu.searchPlaceholder': 'Buscar platos, ingredientes o regiones...',
    'menu.sort': 'Ordenar',
    'menu.dish': 'plato',
    'menu.dishes': 'platos',
    'menu.found': 'encontrados',
    'menu.in': 'en',
    'menu.matching': 'coincidiendo',
    'category.all': 'Todos los Platos',
    'category.sausages': 'Salchichas',
    'category.meat': 'Platos de Carne',
    'category.sides': 'Acompañamientos',
    'category.desserts': 'Postres',
    'home.viewAllDishes': 'Ver Todos los Platos',
    'footer.tagline': 'Cocina alemana auténtica entregada a su mesa. Explore las ricas tradiciones culinarias de Alemania.',
    'footer.navigation': 'Navegación',
    'footer.cookedBy': 'Cocinado con ❤️ por Kabilesh C',
    'cart.itemsLabel': 'Artículos',
    'cart.orderSummary': 'Resumen de Pedido',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Entrega',
    'cart.total': 'Total',
    'checkout.orderSummary': 'Resumen de Pedido',
    'checkout.subtotal': 'Subtotal',
    'checkout.delivery': 'Entrega',
    'checkout.total': 'Total',
    'checkout.confirmationTitle': '¡Pedido Confirmado!',
    'checkout.confirmationMessage': "Gracias por su pedido. Hemos enviado un correo de confirmación a {email}.",
    'checkout.orderNumberMessage': 'Su número de pedido es: {orderNumber}',
    'checkout.returnHome': 'Volver al Inicio',
    'button.viewRecipe': 'Ver Receta',
    'button.addToCart': 'Agregar al Carrito',
    'cart.browseMenu': 'Navegar por el Menú',
  },
  fr: {
    'site.title': 'Guten Eats: Tour Culinaire Allemand',
    'nav.home': 'Accueil',
    'nav.menu': 'Menu',
    'nav.about': 'À Propos',
    'nav.cart': 'Panier',
    'nav.team': 'Équipe',
    'hero.title': 'Découvrez la Cuisine Allemande Authentique',
    'hero.subtitle': 'De la Forêt-Noire à la Bavière, découvrez les saveurs riches de l\'Allemagne',
    'hero.cta': 'Take the GutenEats Tour',
    'dishes.title': 'Plats Traditionnels Allemands',
    'dishes.subtitle': 'Recettes authentiques de toute l\'Allemagne',
    'cart.title': 'Votre Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.checkout': 'Passer à la Caisse',
    'checkout.title': 'Paiement',
    'checkout.name': 'Nom Complet',
    'checkout.email': 'E-mail',
    'checkout.address': 'Adresse de Livraison',
    'checkout.submit': 'Passer la Commande',
    'about.title': 'À Propos de la Cuisine Allemande',
    'about.subtitle': 'Un voyage culinaire à travers l\'histoire et la tradition',
    'about.sustainable.title': 'Nos Objectifs Durables',
    'about.sustainable.description': 'Chez GutenEats, nous nous engageons à des pratiques durables qui soutiennent à la fois les personnes et la planète.',
    'about.heritage.title': 'Le Riche Héritage de la Cuisine Allemande',
    'about.heritage.intro': 'La cuisine allemande varie d\'une région à l\'autre, reflétant l\'histoire fédérale du pays. Chaque région a ses propres traditions culinaires distinctives, reflétant souvent l\'économie locale, l\'histoire culturelle et la géographie.',
    'about.heritage.southern': 'L\'Allemagne du Sud, en particulier la Bavière et la Souabe, est connue pour ses plats copieux avec des boulettes, des pommes de terre et de la viande, en particulier le porc. L\'influence des pays voisins, l\'Autriche et la Suisse, est évidente dans des plats comme le Schnitzel et le Spätzle.',
    'about.regional.title': 'Diversité Régionale',
    'about.regional.northern': 'La cuisine du nord de l\'Allemagne, influencée par la cuisine scandinave, présente des fruits de mer, en particulier le hareng, comme en témoignent des plats comme le Labskaus et la Finkenwerder Scholle. La cuisine de l\'est de l\'Allemagne montre l\'influence des pays slaves et est connue pour ses saveurs copieuses, avec des plats comme la Soljanka et le Sauerbraten.',
    'about.regional.western': 'La cuisine de l\'ouest de l\'Allemagne, en particulier dans la Rhénanie, a été influencée par la cuisine française, particulièrement évidente dans l\'utilisation du vin dans la cuisine et la prédilection pour les asperges blanches. L\'utilisation d\'herbes et d\'épices comme les baies de genièvre, le carvi et la livèche est caractéristique de la cuisine du centre de l\'Allemagne.',
    'about.audio.play': 'Jouer le Guide Audio',
    'about.audio.pause': 'Mettre en Pause le Guide Audio',
    'about.staples.title': 'Pain et Bière: Produits de Base Culturels',
    'about.staples.content': 'Le pain joue un rôle important dans la cuisine allemande, avec plus de 300 variétés de base et 1 200 types différents de pâtisseries et petits pains. Les Allemands consomment environ 80 kg de pain par personne chaque année. La bière est également centrale dans la culture allemande, avec la loi sur la pureté de la bière (Reinheitsgebot) datant de 1516, assurant la qualité et la pureté de la bière allemande.',
    'about.seasonal.title': 'Célébrations Saisonnières',
    'about.seasonal.content': 'La cuisine allemande est étroitement liée aux célébrations saisonnières. L\'Oktoberfest, le plus grand festival de bière au monde, propose des plats spéciaux comme le Hendl (poulet rôti), le Schweinebraten (porc rôti) et le Würstl (saucisses). Les marchés de Noël offrent des friandises saisonnières comme le Lebkuchen (pain d\'épices), le Stollen (pain aux fruits) et le Glühwein (vin chaud).',
    'about.gallery.title': 'Voyage Visuel à Travers la Cuisine Allemande',
    'chatbot.placeholder': 'Posez des questions sur la cuisine allemande...',
    'chatbot.greeting': 'Bonjour ! Je suis Guten Chef, votre assistant de cuisine allemande. Posez-moi des questions sur les plats, les recettes, les ingrédients ou comment passer une commande. Je peux également vous parler des traditions culinaires culturelles !',
    'chatbot.voiceNotSupported': 'Reconnaissance Vocale Non Prise en Charge',
    'chatbot.voiceNotSupportedDesc': 'Votre navigateur ne prend pas en charge la reconnaissance vocale. Veuillez taper votre question.',
    'chatbot.voiceError': 'Erreur de Reconnaissance Vocale',
    'chatbot.listeningStarted': 'Écoute en cours',
    'chatbot.speakNow': 'Veuillez parler maintenant...',
    'chatbot.listening': 'J\'écoute...',
    'chatbot.speakerEnabled': 'Réponses vocales activées',
    'chatbot.speakerDisabled': 'Réponses vocales désactivées',
    'chatbot.microphoneError': 'Erreur de microphone. Veuillez réessayer.',
    'chatbot.microphonePermissionError': 'Veuillez autoriser l\'accès au microphone pour utiliser l\'entrée vocale.',
    'chatbot.welcome': 'Bonjour ! Je suis Guten Chef, votre guide virtuel de la cuisine allemande. Comment puis-je enrichir votre voyage culinaire aujourd\'hui ? Posez-moi des questions sur les plats, les ingrédients, les techniques de cuisine ou passez une commande !',
    'chatbot.title': 'Assistant Guten Chef',
    'chatbot.open': 'Ouvrir l\'assistant de chat',
    'chatbot.micOn': 'Activer le microphone',
    'chatbot.micOff': 'Désactiver le microphone',
    'chatbot.send': 'Envoyer un message',
    'footer.rights': 'Tous Droits Réservés',
    'language': 'Langue',
    'back.to.menu': 'Retour au Menu',
    'recipe.read.aloud': 'Lire la Recette à Haute Voix',
    'recipe.stop.reading': 'Arrêter la Lecture',
    'recipe.ingredients': 'Ingrédients',
    'recipe.preparation': 'Étapes de préparation',
    'recipe.voice.error': 'Erreur de Synthèse Vocale',
    'recipe.voice.error.description': 'Une erreur s\'est produite avec la synthèse vocale. Veuillez réessayer.',
    'members.title': 'Rencontrez la Bande GutenEats 🥨🍺',
    'members.member': 'Membre',
    'members.faculty.title': 'Guide Enseignant',
    'members.faculty.bio': 'Avec plus de 8 ans d\'expérience, Mme Bhuvana Udhayakumar enseigne au Département d\'Anglais et de Langues Étrangères à la Faculté d\'Ingénierie et de Technologie, Campus de Kattankulathur, Chennai. Ses intérêts académiques et de recherche comprennent la Littérature Anglaise, le Féminisme, les Études Culturelles, les Études sur les Femmes et l\'Éco-Féminisme. Elle enseigne également l\'allemand, favorisant la communication interculturelle et donnant aux étudiants des perspectives linguistiques et littéraires.',
    'members.faculty.quote': 'La choucroute de notre schnitzel – donnant saveur et équilibre à tout ce que nous faisons ! 🥬✨',
    'sdg.badge': 'Objectif de Développement Durable',
    'sdg.title': 'FAIM ZÉRO',
    'sdg.description': 'Promouvoir la Faim Zéro grâce au pouvoir de la cuisine traditionnelle allemande. Nuestro proyecto no solo comparte recetas sino que crea conciencia sobre la accesibilidad a los alimentos, prácticas alimentarias sostenibles y apreciación cultural.',
    'sdg.feature1.title': 'Réduction du Gaspillage Alimentaire',
    'sdg.feature1.description': 'Nos recettes incluent des façons créatives d\'utiliser chaque partie des ingrédients et de préserver les aliments de saison.',
    'sdg.feature2.title': 'Accès Équitable à la Nourriture',
    'sdg.feature2.description': 'Nous promouvons des recettes nutritives, abordables et accessibles à toutes les communautés.',
    'sdg.feature3.title': 'Préservation Culturelle',
    'sdg.feature3.description': 'Préserver les traditions culinaires aide à maintenir les connaissances alimentaires à travers les générations.',
    'sdg.button': 'En Savoir Plus Sur la Faim Zéro',
    'cultural.title': 'Unicité de GutenEats',
    'cultural.subtitle': 'Saveur. Patrimoine. Simplicité.',
    'cultural.feature1.title': 'Recettes Authentiques',
    'cultural.feature1.description': 'Nos plats suivent des recettes allemandes traditionnelles transmises de génération en génération.',
    'cultural.feature2.title': 'Ingrédients Frais',
    'cultural.feature2.description': 'Nous utilisons uniquement les ingrédients les plus frais et d\'origine locale pour toutes nos spécialités allemandes.',
    'cultural.feature3.title': 'Expérience Culturelle',
    'cultural.feature3.description': 'Chaque plat est accompagné d\'un contexte culturel et d\'une prononciation audio en plusieurs langues.',
    'cultural.feature4.title': 'Variétés Régionales',
    'cultural.feature4.description': 'Explorez les diverses traditions culinaires des différentes régions allemandes.',
    'about.farm.title': 'De la Ferme à la Table',
    'about.farm.subtitle': 'Soutenir les agriculteurs locaux et réduire les kilomètres alimentaires',
    'about.farm.description': 'Nous nous approvisionnons à 80% en ingrédients auprès de fermes locales dans un rayon de 100 km, réduisant les émissions de carbone tout en soutenant les économies régionales.',
    'about.waste.title': 'Réduction des Déchets',
    'about.waste.subtitle': 'Minimiser notre empreinte environnementale',
    'about.waste.description': 'Grâce au compostage, au recyclage et à une préparation consciente, nous avons réduit nos déchets alimentaires de 65% depuis 2020, travaillant vers zéro déchet d\'ici 2026.',
    'about.culture.title': 'Préservation Culturelle',
    'about.culture.subtitle': 'Honorer les méthodes et recettes traditionnelles',
    'about.culture.description': 'Nous préservons les traditions culinaires allemandes authentiques tout en les adaptant aux pratiques de cuisine contemporaines et durables.',
    'about.hunger.title': 'FAIM ZÉRO',
    'about.hunger.description': 'Nous contribuons fièrement à l\'Objectif de Développement Durable n°2 des Nations Unies : Faim Zéro.',
    'about.hunger.commitment.title': 'Notre Engagement pour la Sécurité Alimentaire',
    'about.hunger.commitment.description': 'GutenEats s\'est associé à des banques alimentaires locales pour donner plus de 10 000 repas par an. Nous croyons que l\'accès à une nourriture nutritive est un droit fondamental pour tous.',
    'about.hunger.initiatives': 'Nos Initiatives Faim Zéro',
    'about.hunger.initiative1': 'Dons hebdomadaires de repas aux refuges communautaires',
    'about.hunger.initiative2': 'Programmes de formation à l\'agriculture durable',
    'about.hunger.initiative3': 'Ateliers éducatifs sur la réduction du gaspillage alimentaire',
    'about.hunger.initiative4': 'Soutien aux petits agriculteurs locaux',
    'about.hunger.initiative5': 'Jardins communautaires dans les déserts alimentaires urbains',
    'about.impact.title': 'Statistiques d\'Impact',
    'about.impact.meals': 'Repas donnés annuellement',
    'about.impact.gardens': 'Jardins communautaires soutenus',
    'about.impact.hours': 'Heures de bénévolat mensuelles',
    'about.impact.farmers': 'Agriculteurs locaux soutenus',
    'chatbot.speechNotSupported': 'La reconnaissance vocale n\'est pas prise en charge dans votre navigateur',
    'chatbot.noSpeechDetected': 'Aucune parole détectée',
    'chatbot.pleaseSpeakClearly': 'Essayez de parler plus clairement ou dans un environnement plus calme',
    'chatbot.microphonePermissionDenied': 'Permission du microphone refusée',
    'chatbot.speechError': 'Erreur de reconnaissance vocale',
    'chatbot.startListeningError': 'Impossible de commencer l\'écoute',
    'chatbot.speechSetupError': 'Impossible de configurer la reconnaissance vocale',
    'chatbot.lowConfidence': 'Incertitude de reconnaissance vocale',
    'chatbot.pleaseReviewBeforeSubmitting': 'Veuillez vérifier le texte avant d\'envoyer',
    'menu.title': 'Expérience Culinaire Allemande',
    'menu.subtitle': "Découvrez les saveurs riches de la cuisine allemande, des plats copieux à base de viande aux délicieux desserts. Toutes nos recettes sont authentiques et préparées selon des méthodes traditionnelles.",
    'menu.searchPlaceholder': 'Rechercher des plats, ingrédients ou régions...',
    'menu.sort': 'Trier',
    'menu.dish': 'plat',
    'menu.dishes': 'plats',
    'menu.found': 'trouvé',
    'menu.in': 'dans',
    'menu.matching': 'correspondant',
    'category.all': 'Tous les Plats',
    'category.sausages': 'Saucisses',
    'category.meat': 'Plats de Viande',
    'category.sides': 'Accompagnements',
    'category.desserts': 'Desserts',
    'home.viewAllDishes': 'Voir Tous les Plats',
    'footer.tagline': "Cuisine allemande authentique livrée à votre table. Découvrez les riches traditions culinaires de l'Allemagne.",
    'footer.navigation': 'Navigation',
    'footer.cookedBy': 'Cuisiné avec ❤️ par Kabilesh C',
    'cart.itemsLabel': 'Articles',
    'cart.orderSummary': 'Récapitulatif de la Commande',
    'cart.subtotal': 'Sous-total',
    'cart.delivery': 'Livraison',
    'cart.total': 'Total',
    'checkout.orderSummary': 'Récapitulatif de la Commande',
    'checkout.subtotal': 'Sous-total',
    'checkout.delivery': 'Livraison',
    'checkout.total': 'Total',
    'checkout.confirmationTitle': 'Commande Confirmée !',
    'checkout.confirmationMessage': "Merci pour votre commande. Nous avons envoyé un e-mail de confirmation à {email}.",
    'checkout.orderNumberMessage': 'Votre numéro de commande est : {orderNumber}',
    'checkout.returnHome': "Retour à l'Accueil",
    'button.viewRecipe': 'Voir Recette',
    'button.addToCart': 'Ajouter au Panier',
    'cart.browseMenu': 'Naviguer dans le Menu',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: defaultLanguage,
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(defaultLanguage);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language | null;
    if (savedLanguage && ['en', 'de', 'es', 'fr'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    localStorage.setItem('language', lang);
    setLanguage(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
