// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iegmsmwsfaqxjwwifjok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZ21zbXdzZmFxeGp3d2lmam9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDExMjAsImV4cCI6MjA1OTU3NzEyMH0.7StyKgZgnaci42xpcMoX7_Mn3y6dUu3hcmTKg1MN-Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);